### PR TITLE
Add vsts nuget feed

### PR DESCRIPTION
**Pull request by calebkiage**
## Summary

Add the VSTS nuget feed to the CLI pipeline

## Generated code differences

None

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/pull/994)

### CODE REVIEW

**Comment by baywet** [comment]
out of curiosity, which package is still private at this point?

**Comment by calebkiage** [comment]
Graph CLI core.

**Comment by calebkiage** [comment]
@baywet, yeah. That's because the package is still early pre-release. I can start the work on publishing it.

**Review by andrueastman — DISMISSED** [review]
I believe we should still be able to publish the package publicly in pre-release. 
In the meantime, I'm good with merging this to unblock PR generations as that is done.

**Comment by calebkiage** [comment]
@baywet, @andrueastman
I've removed the VSTS feed, but the lockfile should be used on the CLI.

**Review by baywet — APPROVED** [review]

**Pull request merged**
