### PR TITLE
Add Option type for NULL fields

### PR DESCRIPTION
**Pull request by meme**
https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/issues/257

### CODE REVIEW

**Comment by meme** [comment]
How can I check if property a is `null`-able?

**Comment by zengin** [comment]
`prop.IsNullable`

**Comment by meme** [comment]
Tried my best to follow the styling~ let me know if any changes need to be made with my indentation.

**Comment by meme** [comment]
Any movement on this?

**Comment by MIchaelMainer** [comment]
This adds `type Option<T> = T | undefined | null;` which then makes these changes:

image

This appears to be a breaking change as the following code results in the following message: `Argument of type '{ id: string; displayName: string; }' is not assignable to parameter of type 'UserIdentity'.
  Type '{ id: string; displayName: string; }' is missing the following properties from type 'UserIdentity': ipAddress, userPrincipalName`

```typescript
export interface UserIdentity {
    // Unique identifier for the identity.
    id: Option<string>;
    // The identity's display name. Note that this may not always be available or up-to-date.
    displayName: Option<string>;
    // Indicates the client IP address used by user performing the activity (audit log only).
    ipAddress: Option<string>;
    // The userPrincipalName attribute of the user.
    userPrincipalName: Option<string>;
}

/* Same issue */
// export interface UserIdentity {
//     // Unique identifier for the identity.
//     id: string | null | undefined;
//     // The identity's display name. Note that this may not always be available or up-to-date.
//     displayName: string | null | undefined;
//     // Indicates the client IP address used by user performing the activity (audit log only).
//     ipAddress: string | null | undefined;
//     // The userPrincipalName attribute of the user.
//     userPrincipalName: string | null | undefined;
// }

/* Original - this shows no warnings from TS */
// export interface UserIdentity {
//     // Unique identifier for the identity.
//     id?: string;
//     // The identity's display name. Note that this may not always be available or up-to-date.
//     displayName?: string;
//     // Indicates the client IP address used by user performing the activity (audit log only).
//     ipAddress?: string;
//     // The userPrincipalName attribute of the user.
//     userPrincipalName?: string;
// }

type Option<T> = T | undefined | null;

function printId(userIdentity: UserIdentity) {
    console.log(userIdentity.id);
}

// let myObj = { id: "10", displayName: "Size 10 Object", ipAddress: null, userPrincipalName: null };
let myObj = { id: "10", displayName: "Size 10 Object" };

printId(myObj);
```

@meme Can you help me understand what I see here?

**Comment by meme** [comment]
This was an oversight~ since `undefined` is embedded in the type, it does not act the same as an optional field with, e.g.: `name?: string`. I have corrected this issue in my latest commit, so your example should now work correctly.

**Comment by zengin** [comment]
To cover the point I mentioned in my review, dot notation in VSCode auto-complete doesn't break with this change.

**Comment by MIchaelMainer** [comment]
closes #257

**Pull request merged**
