### PR TITLE
Add codegen commit info to generated files

### PR DESCRIPTION
**Pull request by kevklam**
Adds commit info to license header so it looks like the following:

```
// ------------------------------------------------------------------------------
// Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the MIT License.  See License in the project root for license information.
// 
// CodeGen: 9a20d7e0e0fea939d753d81dbf9d496e289201ab
// ------------------------------------------------------------------------------
```

### CODE REVIEW

**Comment by shiftylogic** [comment]
Does this change run on a Mac? This is a requirement for us.

**Comment by kevklam** [comment]
Do you have instructions for building with Mono? I cloned the repo and submodules, installed Mono and ran mono_build.sh, but it is failing (without my changes) with the following message:
```
(Build target) ->
				/Users/kevinlam/Dev/OneDrive/MSGraph-SDK-Code-Generator/submodules/vipr/test/Shared/ODataV4TestService/ODataV4TestService.csproj (default targets) ->
				/Library/Frameworks/Mono.framework/Versions/4.4.2/lib/mono/xbuild/12.0/bin/Microsoft.CSharp.targets (CoreCompile target) ->
					CSC: error CS1904: `2008' is not a valid warning number
					CSC: error CS1904: `1684' is not a valid warning number
				/Users/kevinlam/Dev/OneDrive/MSGraph-SDK-Code-Generator/submodules/vipr/Vipr.sln (build) ->
				(Build target) ->
				/Users/kevinlam/Dev/OneDrive/MSGraph-SDK-Code-Generator/submodules/vipr/test/Shared/MockService/MockService.csproj (default targets) ->
				/Library/Frameworks/Mono.framework/Versions/4.4.2/lib/mono/xbuild/12.0/bin/Microsoft.CSharp.targets (CoreCompile target) ->
					CSC: error CS1904: `2008' is not a valid warning number
					CSC: error CS1904: `1684' is not a valid warning number
					 4 Warning(s)
					 4 Error(s)
				Time Elapsed 00:00:03.3948670
/Library/Frameworks/Mono.framework/Versions/4.4.2/lib/mono/xbuild/12.0/bin/Microsoft.Common.targets: error : Command 'xbuild /t:build /p:Configuration=Debug "/Users/kevinlam/Dev/OneDrive/MSGraph-SDK-Code-Generator/src/GraphODataTemplateWriter/../../submodules/vipr/Vipr.sln"' exited with code: 1.
```

**Comment by shiftylogic** [comment]
Provided you have mono installed, that is all you have to do. The mono_build script should build clean.

If it is failing without your changes, then someone broke something. I'll try it out sometime before Monday and get back to you.

**Comment by shiftylogic** [comment]
I attempted to pull your changes into the master branch on my mac. It appears that nuget on the mac has issues pulling that libgit2sharp package. You might want to start your investigation there.

**Comment by kevklam** [comment]
What version of Mono are you using? The version I got from [here](http://www.mono-project.com/download/) does not recognize warning 1684, referenced in the following:
```
./submodules/vipr/samples/SharePoint/src/Microsoft.Office365.SharePoint.csproj:    <NoWarn>;1684</NoWarn>
./submodules/vipr/test/Shared/MockService/MockService.csproj:    <NoWarn>;2008;1998;1684</NoWarn>
./submodules/vipr/test/Shared/ODataV4TestService/ODataV4TestService.csproj:    <NoWarn>;2008;1998;1684</NoWarn>```

**Comment by kevklam** [comment]
I did some trial and error, and it looks like between Mono 4.2.4 and 4.3.2 they changed this warning to an error (latest version is 4.4.2). Either of the following allows me to build:

1. Removing the '2008' and '1684' entries from the vipr submodule. I can submit a PR for this if you want, the code builds on both Mono 4.2.4 and 4.4.2 with this change though I haven't checked if this will cause more warnings to appear when building in VS.
2. Downgrading to Mono 4.2.4 (warnings still appear but do not cause the build to fail).

I then performed the additional step of adding my personal repo as a remote and merging the change from this PR. On my machine, the nuget package for libgit2sharp installed without issues when running mono_build.sh:
```
            Target RestorePackages:
                Executing: mono --runtime=v4.0.30319 "/Users/kevinlam/Dev/OneDrive/MSGraph-SDK-Code-Generator/.nuget/NuGet.exe" install "/Users/kevinlam/Dev/OneDrive/MSGraph-SDK-Code-Generator/src/GraphODataTemplateWriter/packages.config" -source ""   -RequireConsent -solutionDir "/Users/kevinlam/Dev/OneDrive/MSGraph-SDK-Code-Generator/"
                Restoring NuGet packages...
                To prevent NuGet from downloading packages during build, open the Visual Studio Options dialog, click on the Package Manager node and uncheck 'Allow NuGet to download missing packages'.
                Installing 'LibGit2Sharp 0.22.0'.
                Successfully installed 'LibGit2Sharp 0.22.0'.
                Installing 'LibGit2Sharp.NativeBinaries 1.0.129'.
                Successfully installed 'LibGit2Sharp.NativeBinaries 1.0.129'.
```

What is the issue you're running into with libgit2sharp on mac?

**Comment by kevklam** [comment]
@shiftylogic Just wanted to ping on this.

**Comment by shiftylogic** [comment]
I'll merge this change. Please submit a PR to VIPR to remove those 2 warnings. This will get tested on Windows as we work. Cursory digging on this issue shows that this was an issue for VS2008 pre-update1. So, it should be a non-issue for us moving forward.

**Comment by shiftylogic** [comment]
Never mind about the PR on VIPR. I submitted it with a fix for the Jenkins build issue.

**Comment by zengin** [comment]
Linked this PR from the SourceLink issue. We will keep this PR as a reference if we need the commit information for other languages.

**Pull request closed without merging**
