### PR TITLE
feature/java orderby

### PR DESCRIPTION
**Pull request by baywet**
## Generated code differences

https://github.com/microsoftgraph/msgraph-sdk-java/pull/503

### CODE REVIEW

**Review by zengin — COMMENTED** [review]
@baywet Do you have an example where `orderBy` is used on a non-collection? I looked at couple of OData docs and all the samples I saw were on collections even though they don't say the clause is exclusive to collections, e.g. https://docs.microsoft.com/en-us/odata/concepts/queryoptions-overview#orderby

**Comment by baywet** [comment]
good catch. I think you're referring to these two templates specifically?
https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/blob/56a5b257af6c0188fa97db6ce08346819f4120aa/Templates/Java/requests_extensions/BaseEntityRequest.java.tt
https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/blob/56a5b257af6c0188fa97db6ce08346819f4120aa/Templates/Java/requests_extensions/BaseEntityWithReferenceRequest.java.tt

I think what happened is that when I introduced filter, I did a search for expand. And went a bit too far. 
And the same thing happened for orderBy but with filter this time. I think both odata query parameters functions should be removed from these two.

Did I miss anything else?

**Comment by zengin** [comment]
I think we should remove `orderBy` from all these as they are not operating on collections:
```
Templates/Java/requests_extensions/BaseEntityReferenceRequest.java.tt 
Templates/Java/requests_extensions/BaseEntityRequest.java.tt 
Templates/Java/requests_extensions/BaseEntityWithReferenceRequest.java.tt 
Templates/Java/requests_extensions/BaseMethodBodyRequest.java.tt 
Templates/Java/requests_extensions/BaseMethodRequest.java.tt 
```

**Comment by baywet** [comment]
thanks! updated, sorry about the mess.

**Review by zengin — APPROVED** [review]

**Pull request merged**
