### PR TITLE
Set Hidi version to 1.0.0-preview1

### PR DESCRIPTION
**Pull request by andrueastman**
This PR provides a temporary fix to unblock openApi generation for Kiota based SDKs

It sets the hidi version to `1.0.0-preview1` pending the resolution of https://github.com/microsoft/OpenAPI.NET/issues/866

Once the issue has been resolved, we can do a simple reverting of this PR.

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/pull/756)

### CODE REVIEW

**Review by baywet — CHANGES_REQUESTED** [review]
This will cause regressions on v1 sdks, I'd argue we should fix the issue instead or at least make the version a pipeline variable

**Comment by andrueastman** [comment]
> This will cause regressions on v1 sdks, I'd argue we should fix the issue instead or at least make the version a pipeline variable

Thanks @baywet,
Any chance you can expound on the regressions for v1 SDKs? My understanding is that we haven't really used a version higher than `1.0.0-preview1` so we would be maintaining the latest used version.

**Comment by baywet** [comment]
After looking into this further, it seems that indeed [the last version used for generation last week was 1.0.0-preview1](https://microsoftgraph.visualstudio.com/Graph%20Developer%20Experiences/_build/results?buildId=74322&view=logs&j=c76a6dd1-275b-590a-9134-f144ba77623c&t=742f67dc-f717-5e08-b236-c862e7a541e7)

From preview1 to preview3 the [biggest change seems to be the upgrade of OpenApi.net.odata from 1.0.10-preview3 to 1.0.10](https://github.com/microsoft/OpenAPI.NET/compare/5eb148183950ef24132a070da19cc088124aa4fe...3b66e24e6034c097f5abc22323d13e49e856d605)

From OpenApi.net.Odata 1.0.10-preview3 to 1.0.10 the [biggest change seems to be for the odata typecast expansion](https://github.com/microsoft/OpenAPI.NET.OData/compare/4e000501ed5978b9a537deb01168ca20855670c3...04422bf67138891b6bc6822357a8686061ba608e)

Before we commit to locking the tool version as a workaround, would you mind running hidi locally while setting `ExpandDerivedTypesNavigationProperties` to false in the OpenAPIConvertSettings please to validate the hypothesis?

**Comment by andrueastman** [comment]
> After looking into this further, it seems that indeed [the last version used for generation last week was 1.0.0-preview1](https://microsoftgraph.visualstudio.com/Graph%20Developer%20Experiences/_build/results?buildId=74322&view=logs&j=c76a6dd1-275b-590a-9134-f144ba77623c&t=742f67dc-f717-5e08-b236-c862e7a541e7)
> 
> From preview1 to preview3 the [biggest change seems to be the upgrade of OpenApi.net.odata from 1.0.10-preview3 to 1.0.10](https://github.com/microsoft/OpenAPI.NET/compare/5eb148183950ef24132a070da19cc088124aa4fe...3b66e24e6034c097f5abc22323d13e49e856d605)
> 
> From OpenApi.net.Odata 1.0.10-preview3 to 1.0.10 the [biggest change seems to be for the odata typecast expansion](https://github.com/microsoft/OpenAPI.NET.OData/compare/4e000501ed5978b9a537deb01168ca20855670c3...04422bf67138891b6bc6822357a8686061ba608e)
> 
> Before we commit to locking the tool version as a workaround, would you mind running hidi locally while setting `ExpandDerivedTypesNavigationProperties` to false in the OpenAPIConvertSettings please to validate the hypothesis?

No worries @baywet . I'll work on this and give feedback on my findings.

**Comment by andrueastman** [comment]
> Would you mind regrouping with @irvinesunday to try to nail down this issue (option 3) ? let's timebox the effort to 1 hour, and if after that it's not resolved, what do you think about option 2 instead of locking the tool version

That makes sense. Now that we understand where the issue could be, option 2 sounds good. Closing this for now and we'll rerun generation once we settle on option 2 or 3.

**Pull request closed without merging**
