### PR TITLE
Support composable functions in .NET

### PR DESCRIPTION
**Pull request by MIchaelMainer**
## Summary

Composable functions are functions that can be composed with additional URL segments that represent either navigation properties or OData methods. The composition is based on the return type of the composable function. We need to make sure we support the following:

- [x] Composition based on navigation properties of the return type. In this case, the WorkbookWorksheetRangeRequestBuilder gets `Format`, `Sort`, and ` Worksheet` properties that return request builders.

```xml
<Function Name="range" IsBound="true" IsComposable="true">
  <Parameter Name="bindparameter" Type="graph.workbookWorksheet" />
  <ReturnType Type="graph.workbookRange" />
</Function>

<EntityType Name="workbookRange" BaseType="graph.entity">
  <NavigationProperty Name="format" Type="graph.workbookRangeFormat" ContainsTarget="true" />
  <NavigationProperty Name="sort" Type="graph.workbookRangeSort" ContainsTarget="true" />
  <NavigationProperty Name="worksheet" Type="graph.workbookWorksheet" ContainsTarget="true" />
</EntityType>
```

- [x] Composition based on actions bound to the return type. In this case, the WorkbookWorksheetRangeRequestBuilder gets `Clear()`, `Delete()`, `Insert()`, `Merge()`, and `Unmerge()` methods applied for the actions bound to the workbookRange entity.

```xml

<Action Name="clear" IsBound="true">
  <Parameter Name="bindparameter" Type="graph.workbookRange" />
  <Parameter Name="applyTo" Type="Edm.String" Nullable="false" Unicode="false" />
</Action>
<Action Name="delete" IsBound="true">
  <Parameter Name="bindparameter" Type="graph.workbookRange" />
  <Parameter Name="shift" Type="Edm.String" Nullable="false" Unicode="false" />
</Action>
<Action Name="insert" IsBound="true">
  <Parameter Name="bindparameter" Type="graph.workbookRange" />
  <Parameter Name="shift" Type="Edm.String" Nullable="false" Unicode="false" />
  <ReturnType Type="graph.workbookRange" />
</Action>
<Action Name="merge" IsBound="true">
  <Parameter Name="bindparameter" Type="graph.workbookRange" />
  <Parameter Name="across" Type="Edm.Boolean" Nullable="false" />
</Action>
<Action Name="unmerge" IsBound="true">
  <Parameter Name="bindparameter" Type="graph.workbookRange" />
</Action>

```

- [x] Composition based on functions bound to the return type. In this case, the WorkbookWorksheetRangeRequestBuilder gets 23 methods applied for the functions bound to the workbookRange entity. Here's a couple of examples.

```xml
<Function Name="boundingRect" IsBound="true" IsComposable="true">
  <Parameter Name="bindparameter" Type="graph.workbookRange" />
  <Parameter Name="anotherRange" Type="Edm.String" Unicode="false" />
  <ReturnType Type="graph.workbookRange" />
</Function>
<Function Name="cell" IsBound="true" IsComposable="true">
  <Parameter Name="bindparameter" Type="graph.workbookRange" />
  <Parameter Name="row" Type="Edm.Int32" Nullable="false" />
  <Parameter Name="column" Type="Edm.Int32" Nullable="false" />
  <ReturnType Type="graph.workbookRange" />
</Function>

```

- [x] Respect whether the binding parameter is bound to a collection or a single entity. In this case, we'll use WorkbookChart entity since this entity is bound individually with an `Image()` overloaded function, as well is being bound as a collection for the `Count()`, `Item()`, and `ItemAt()` functions, and the `Add()` action. For the first case (bound to a single entity), we generate a WorkbookChartImageRequestBuilder which is referenced in WorkbookChartRequestBuilder. For the second case (bound to a collection of entities), we generate a WorkbookWorksheetChartsCollectionRequestBuilder that contains the four methods which is accessible via the WorkbookWorksheetRequestBuilder. 

```xml
<!-- Bound to single entity -->
<Function Name="image" IsBound="true">
  <Parameter Name="bindparameter" Type="graph.workbookChart" />
  <ReturnType Type="Edm.String" Unicode="false" />
</Function>
<Function Name="image" IsBound="true">
  <Parameter Name="bindparameter" Type="graph.workbookChart" />
  <Parameter Name="width" Type="Edm.Int32" Nullable="false" />
  <ReturnType Type="Edm.String" Unicode="false" />
</Function>
<Function Name="image" IsBound="true">
  <Parameter Name="bindparameter" Type="graph.workbookChart" />
  <Parameter Name="width" Type="Edm.Int32" Nullable="false" />
  <Parameter Name="height" Type="Edm.Int32" Nullable="false" />
  <ReturnType Type="Edm.String" Unicode="false" />
</Function>
<Function Name="image" IsBound="true">
  <Parameter Name="bindparameter" Type="graph.workbookChart" />
  <Parameter Name="width" Type="Edm.Int32" Nullable="false" />
  <Parameter Name="height" Type="Edm.Int32" Nullable="false" />
  <Parameter Name="fittingMode" Type="Edm.String" Nullable="false" Unicode="false" />
  <ReturnType Type="Edm.String" Unicode="false" />
</Function>

<!-- Bound to entity collection -->
<Function Name="count" IsBound="true">
  <Parameter Name="bindparameter" Type="Collection(graph.workbookChart)" />
  <ReturnType Type="Edm.Int32" Nullable="false" />
</Function>
<Function Name="item" IsBound="true" IsComposable="true">
  <Parameter Name="bindparameter" Type="Collection(graph.workbookChart)" />
  <Parameter Name="name" Type="Edm.String" Unicode="false" />
  <ReturnType Type="graph.workbookChart" />
</Function>
<Function Name="itemAt" IsBound="true" IsComposable="true">
  <Parameter Name="bindparameter" Type="Collection(graph.workbookChart)" />
  <Parameter Name="index" Type="Edm.Int32" Nullable="false" />
  <ReturnType Type="graph.workbookChart" />
</Function>
<Action Name="add" IsBound="true">
  <Parameter Name="bindparameter" Type="Collection(graph.workbookChart)" />
  <Parameter Name="type" Type="Edm.String" Nullable="false" Unicode="false" />
  <Parameter Name="sourceData" Type="graph.Json" />
  <Parameter Name="seriesBy" Type="Edm.String" Nullable="false" Unicode="false" />
  <ReturnType Type="graph.workbookChart" />
</Action>

```

- [x] Check whether their are considerations for binding to reference entities or entity collections. We don't generate for this and I don't think we should. The reference scenarios in many cases are cross workload scenarios and composability cross workloads sounds like something we wouldn't have at this time. It would be straightforward to add I think if we encounter this scenario. 

```xml
<EntityType Name="invitation" BaseType="graph.entity">
  <NavigationProperty Name="invitedUser" Type="graph.user" />
</EntityType>
```

- [x] Make sure composable function request builders support IBaseRequestBuilder. Function request builders derive from BaseFunctionMethodRequestBuilder and actions from BaseActionMethodRequestBuilder. Both derive from BaseRequestBuilder which is an IBaseRequestBuilder. Adding IBaseRequestBuilder as the common interface for all method request builders so that we can resolve https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/issues/266. 

- [x] Make sure that composable functions can pass in arguments at each composed segment.
- [x] rebase on dev
- [x] SetFunctionParameters() is set on every function request builder cstor.

## Generated code differences

TBD

## Command line arguments to run these changes

-v Info -m https://raw.githubusercontent.com/microsoftgraph/msgraph-metadata/master/clean_v10_metadata/cleanMetadataWithDescriptionsv1.0.xml -o composableWithNav -l CSharp -g Files

## Query the metadata with LinqPad

```csharp
string v1_0 = "https://graph.microsoft.com/v1.0/$metadata";
string metadata = new WebClient().DownloadString(v1_0);
XElement xMetadata = XElement.Parse(metadata);

// Get all actions bound to a type
xMetadata.Descendants("{http://docs.oasis-open.org/odata/ns/edm}Action")
		 .Where(m => m.Descendants("{http://docs.oasis-open.org/odata/ns/edm}Parameter")
		 	.First()
			.Attributes("Type")
			.Any(x => x.Value.Equals("graph.workbookRange")))
		 .Dump("All actions to bound workbookRange");

xMetadata.Descendants("{http://docs.oasis-open.org/odata/ns/edm}Function")
		 .Where(m => m.Attributes("IsComposable").Any())
		 .Where(m => m.Descendants("{http://docs.oasis-open.org/odata/ns/edm}ReturnType")
			.Attributes("Type")
			.Any(x => !x.Value.Contains("graph.report")))
		 .Dump("All composable functions without report root");

// Get all functions bound to a type
xMetadata.Descendants("{http://docs.oasis-open.org/odata/ns/edm}Function")
		 .Where(m => m.Descendants("{http://docs.oasis-open.org/odata/ns/edm}Parameter")
		 	.First()
			.Attributes("Type")
			.Any(x => x.Value.Equals("graph.workbookRange")))
		 .Dump("All functions to bound workbookRange");

```

## Links to issues or work items this PR addresses

https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/issues/175

### CODE REVIEW

**Comment by michael-hawker** [comment]
This is the work to help resolve #266, eh?

**Comment by MIchaelMainer** [comment]
Thanks at @michael-hawker for linking that. I added a requirement that they implement IBaseRequestBuilder.

**Comment by baywet** [comment]
@MIchaelMainer do you mind rebasing on dev please? it looks like you created your branch from master, I just want to make sure we don't run into weird merging issues at the end. Thanks!

**Comment by MIchaelMainer** [comment]
Raptor v1 results finds existing issues with the following scenarios:

Function overloads with zero and 1 argument only generates the zero argument version.

await graphClient.Me.Drive.Root.Workbook.Worksheets["{id}"]
    .Range()
    .RowsAbove(null)
    .Request()
    .PostAsync();

var workbookRange = await graphClient.Me.Drive.Items["{id}"].Workbook.Names["{name}"]
    .Range()
    .UsedRange(true)
    .Request()
    .GetAsync();

Actions bound to a collection don't generate the method.

await graphClient.Users["{user-id}"].FollowedSites
    .Add(value)
    .Request()
    .PostAsync();

await graphClient.Users["{user-id}"].FollowedSites
    .Remove(value)
    .Request()
    .PostAsync();

**Comment by MIchaelMainer** [comment]
Will merge dev into this after @baywet merges all tool chain for NET Core support.

**Comment by MIchaelMainer** [comment]
- [ ] Wait on the .NET Core changes, bring those in to validate, then we can merge.

**Comment by MIchaelMainer** [comment]
I need review on this.

**Comment by baywet** [comment]
@MIchaelMainer can you please resolve conflicts on this one before we review it? this way our reviews won't get dismissed.

**Comment by baywet** [comment]
@MIchaelMainer closing this one to avoid any confusion

**Pull request closed without merging**
