### PR TITLE
Removing warnings about accessing 'Type' property and moving to using…

### PR DESCRIPTION
**Pull request by shiftylogic**
… the 'Projection' of a type for CSharp / Android / JavaScript.

The works still needs to be done for ObjC and Python, but I don't have an environment setup to test it so I'll get to it a bit later.

### CODE REVIEW

**Comment by peternied** [comment]
RE: ObjC and Python, you just need to make sure the template output before and after this PR is identical, no need to perform any deeper testing.

**Comment by shiftylogic** [comment]
Ok... git me a bit and I'll make those changes as well.

**Comment by shiftylogic** [comment]
ObjC done.

Python has a crashing issue. It appears that even the master branch version is broken. I'll reach out to Travis to have a look at it.

**Comment by peternied** [comment]
@shiftylogic Lets just bug the Python changes since that area is in flight

**Comment by shiftylogic** [comment]
I filed an issue to track the Python Type to Projection change.

**Pull request merged**
